### ISSUE TITLE
TypeCastError from #page_source

### ISSUE THREAD

**Issue by mcarpenter** [watzon/marionette#29]
Hi,

I suspect I'm doing something wrong here but I can't see it. What am I missing?

### Test case

`foo.cr`:
```crystal
require "marionette"

session = Marionette::WebDriver.create_session(:chrome)
session.navigate("https://example.com")
puts session.page_source
```

`shard.yml`:
```yaml
name: foo
version: 0.0.1

targets:
  foo:
    main: foo.cr

dependencies:
  marionette:
    github: watzon/marionette
    branch: master

crystal: 1.0.0

license: MIT
```

### Error

```
martin:/tmp$ shards install
Resolving dependencies
Fetching https://github.com/watzon/marionette.git
Installing marionette (0.3.0 at a962bb3)
Writing shard.lock
martin:/tmp$
martin:/tmp$ crystal --version
Crystal 1.0.0 [dd40a2442] (2021-03-22)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
martin:/tmp$
martin:/tmp$ crystal foo.cr
Unhandled exception: cast from Hash(String, JSON::Any) to String failed, at /usr/share/crystal/src/json/any.cr:215:5:215 (TypeCastError)
  from /usr/share/crystal/src/json/any.cr:214:3 in 'as_s'
  from lib/marionette/src/marionette/session.cr:356:7 in 'page_source'
  from foo.cr:5:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???
martin:/tmp$ 
```
